# DeepSeek R1 1.5B Configuration
name: "deepseek-r1:1.5b"

resources:
  gpu_layers: 32
  gpu_memory: "4GB"
  batch_size: 12
  max_concurrent: 4

parameters:
  temperature: 0.7
  top_p: 0.9
  max_tokens: 2048
  stop_sequences: ["<|begin▁of▁sentence|>", "<|end▁of▁sentence|>"]  # Default stop sequences from Ollama

system:
  prompt: "You are a helpful AI assistant. You are direct, accurate, and helpful in your responses."

validation:
  temperature_range: [0.0, 1.0]
  max_tokens_limit: 4096
  batch_size_range: [1, 24]
  concurrent_range: [1, 8]

# Resource Requirements
requirements:
  min_gpu_memory: "4GB"  # Minimum required for safe operation
  recommended_gpu: "A100"
  cuda_version: ">=11.7"
  cpu_threads: 2
  gpu_memory_utilization: 0.9 