# DeepSeek R1 671B Configuration
name: "deepseek-r1:671b"

resources:
  gpu_layers: 128
  gpu_memory: "400GB"
  batch_size: 1
  max_concurrent: 1

parameters:
  temperature: 0.7
  top_p: 0.9
  max_tokens: 2048
  stop_sequences: ["<|begin▁of▁sentence|>", "<|end▁of▁sentence|>"]  # Default stop sequences from Ollama

system:
  prompt: "You are a helpful AI assistant. You are direct, accurate, and helpful in your responses."

validation:
  temperature_range: [0.0, 1.0]
  max_tokens_limit: 4096
  batch_size_range: [1, 2]
  concurrent_range: [1, 1]

# Resource Requirements
requirements:
  min_gpu_memory: "400GB"  # Minimum required for safe operation
  recommended_gpu: "H100"
  cuda_version: ">=12.0"
  cpu_threads: 16
  gpu_memory_utilization: 0.9 